name: Build Android APK (Manual Setup)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install system dependencies (incl. AIDL)
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool build-essential \
          zlib1g-dev libncurses5-dev libncursesw5-dev libsqlite3-dev libssl-dev libffi-dev \
          libjpeg-dev libfreetype6-dev python3-pip libstdc++6 aidl
          
    - name: Set AIDL path manually
      run: |
        export AIDL_PATH=$ANDROID_HOME/build-tools/33.0.2/aidl
        echo "AIDL path: $AIDL_PATH"
        if [ ! -f "$AIDL_PATH" ]; then
          echo "AIDL ainda não encontrado em $AIDL_PATH"
          exit 1
        fi
        echo "buildozer: Setting AIDL path manually"
        mkdir -p ~/.buildozer/android/platform/android-sdk/build-tools/33.0.2/
        ln -s "$AIDL_PATH" ~/.buildozer/android/platform/android-sdk/build-tools/33.0.2/aidl

    - name: Install Buildozer and Python deps
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade buildozer==1.5.0 cython==3.0.10 setuptools

    - name: Install Android SDK and set environment
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        cd $HOME/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-10406996_latest.zip -O tools.zip
        unzip tools.zip
        mv cmdline-tools latest
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept Licenses and Install Android Packages
      run: |
        yes | sdkmanager --licenses
        sdkmanager --install "cmdline-tools;latest"
        sdkmanager --install "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653" "extras;android;m2repository"
        ls -la $ANDROID_HOME/build-tools/33.0.2/aidl || echo "AIDL NÃO ENCONTRADO"

    - name: Create buildozer.spec
      run: |
        cat << EOF > buildozer.spec
        [app]
        title = PyFlora Estoque
        package.name = pyflora
        package.domain = com.meuapp
        source.dir = .
        source.include_exts = py,png,jpg,kv,ttf
        version = 1.0
        requirements = python3,kivy==2.3.0,https://github.com/kivy/kivy_garden.graph/archive/master.zip,pillow,qrcode,pyzbar,opencv-python,openpyxl,fpdf,pyjnius==1.6.1
        orientation = portrait
        android.permissions = CAMERA,INTERNET

        [buildozer]
        log_level = 2
        warn_on_root = 1

        android.api = 34
        android.minapi = 21
        android.ndk = 25.2.9519653
        android.ndk_path = /home/runner/android-sdk/ndk/25.2.9519653
        android.sdk_path = /home/runner/android-sdk
        android.accept_sdk_license = True
        EOF

    - name: Verificar sdkmanager e aidl
      run: |
        echo "Verificando SDK instalado..."
        ls -la $ANDROID_HOME/build-tools/33.0.2/
        ls -la $ANDROID_HOME/cmdline-tools/latest/bin/
        
    - name: Instalar NDK manualmente
      run: |
        export ANDROID_HOME=$HOME/android-sdk
        export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager "ndk;25.2.9519653"

    - name: Build APK
      run: buildozer -v android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
