name: Build Android APK (Final Attempt on Ubuntu 22.04)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool build-essential zlib1g-dev libncurses5-dev libncursesw5-dev

    - name: Install Buildozer and Dependencies
      run: pip install --upgrade buildozer==1.5.0 cython==3.0.10 setuptools

    - name: Create buildozer.spec
      run: |
        cat << EOF > buildozer.spec
        [app]
        title = PyFlora Estoque
        package.name = pyflora
        package.domain = com.meuapp
        source.dir = .
        source.include_exts = py,png,jpg,kv,ttf
        version = 1.0
        requirements = python3,kivy==2.3.0,https://github.com/kivy/kivy_garden.graph/archive/master.zip,pillow,qrcode,pyzbar,opencv-python,openpyxl,fpdf,pyjnius==1.6.1
        orientation = portrait
        android.permissions = CAMERA,INTERNET

        [buildozer]
        log_level = 2
        warn_on_root = 1

        android.api = 34
        android.minapi = 21
        android.ndk = 25b
        EOF

    - name: Build APK with Buildozer Action
      uses: kivy/buildozer-action@v1.0.0
      with:
        command: buildozer android debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
