name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip autoconf automake libtool build-essential zlib1g-dev libncurses5-dev libncursesw5-dev

    - name: Set up Android SDK in Buildozer's Default Location
      run: |
        # Cria a estrutura de pastas exata que o Buildozer espera
        mkdir -p $HOME/.buildozer/android/platform

        # Define o caminho do SDK para este local
        SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"
        echo "ANDROID_HOME=${SDK_ROOT}" >> $GITHUB_ENV
        
        # Baixa e descompacta as ferramentas de linha de comando
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        mkdir -p ${SDK_ROOT}/cmdline-tools
        unzip cmdline-tools.zip -d ${SDK_ROOT}/cmdline-tools
        mv ${SDK_ROOT}/cmdline-tools/cmdline-tools ${SDK_ROOT}/cmdline-tools/latest
        
        # Adiciona as ferramentas ao PATH do sistema
        echo "${SDK_ROOT}/cmdline-tools/latest/bin" >> $GITHUB_PATH
        echo "${SDK_ROOT}/platform-tools" >> $GITHUB_PATH
        
        # Instala os pacotes do SDK
        yes | ${SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Install Buildozer and Dependencies
      run: pip install --upgrade buildozer cython setuptools

    - name: Create buildozer.spec
      run: |
        cat << EOF > buildozer.spec
        [app]
        title = PyFlora Estoque
        package.name = pyflora
        package.domain = com.meuapp
        source.dir = .
        source.include_exts = py,png,jpg,kv,ttf
        version = 1.0
        requirements = python3,kivy==2.3.0,https://github.com/kivy/kivy_garden.graph/archive/master.zip,pillow,qrcode,pyzbar,opencv-python,openpyxl,fpdf,pyjnius==1.6.1
        orientation = portrait
        android.permissions = CAMERA,INTERNET

        [buildozer]
        log_level = 2
        warn_on_root = 1

        p4a.branch = master

        # A linha android.sdk_path foi REMOVIDA, pois agora não é mais necessária

        android.api = 34
        android.minapi = 21
        android.ndk = 25b
        EOF

    - name: Build with Buildozer
      run: buildozer -v android debug

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: apk
        path: bin/*.apk
